## RECONOCIMIENTO DE PATRONES - TYPES OF GLASS

In [19]:
# Loading the data using pandas.

In [20]:
import pandas as pd

In [21]:
input_folder = "../input/"
# RI, Na, Mg, Al, Si, K, Ca, Ba, Fe
inputs_name = "glassInputs.csv"
targets_name = "glassTargets.csv"

In [22]:
inputs_data = pd.read_csv(input_folder + inputs_name)
targets_data = pd.read_csv(input_folder + targets_name)

In [23]:
inputs_data

      1.521  13.64  4.49   1.1  71.78  0.06  8.75     0   0.1
0    1.5176  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00
1    1.5162  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00
2    1.5177  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00
3    1.5174  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00
4    1.5160  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26
..      ...    ...   ...   ...    ...   ...   ...   ...   ...
208  1.5162  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00
209  1.5169  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.00
210  1.5207  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.00
211  1.5165  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.00
212  1.5171  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.00

[213 rows x 9 columns]